[package]
name = "sphere-vis"
version = "0.1.0"
authors = ["alexge50 <alexge50.x@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "^0.14.0"
glium = "*"
glm = "^0.2.3"